// lucide-react
import {
  Coffee,
  Crown,
  Heart,
  Moon,
  Music,
  Palette,
  Rocket,
  Smile,
  Sparkles,
  Star,
  Sun,
  Zap,
} from "lucide-react";

const cartoonAvatars = [
  {
    id: 0,
    character: "Sunny",
    emoji: "😊",
    color: "#030213",
    bgGradient: "from-yellow-300 to-yellow-400",
    personality: "Optimistic",
    icon: Sun,
    description: "Always bright and cheerful",
  },
  {
    id: 1,
    character: "Luna",
    emoji: "🌙",
    color: "#030213",
    bgGradient: "from-yellow-500 to-yellow-600",
    personality: "Dreamy",
    icon: Moon,
    description: "Creative and thoughtful",
  },
  {
    id: 2,
    character: "Spark",
    emoji: "⚡",
    color: "#030213",
    bgGradient: "from-yellow-300 to-yellow-400",
    personality: "Energetic",
    icon: Zap,
    description: "Full of energy and ideas",
  },
  {
    id: 3,
    character: "Royal",
    emoji: "👑",
    color: "#030213",
    bgGradient: "from-yellow-300 to-yellow-400",
    personality: "Confident",
    icon: Crown,
    description: "Natural born leader",
  },
  {
    id: 4,
    character: "Artist",
    emoji: "🎨",
    color: "#030213",
    bgGradient: "from-amber-500 to-amber-600",
    personality: "Creative",
    icon: Palette,
    description: "Loves art and beauty",
  },
  {
    id: 5,
    character: "Rocket",
    emoji: "🚀",
    color: "#030213",
    bgGradient: "from-red-300 to-red-400",
    personality: "Ambitious",
    icon: Rocket,
    description: "Reaches for the stars",
  },
  {
    id: 6,
    character: "Melody",
    emoji: "🎵",
    color: "#030213",
    bgGradient: "from-gray-300 to-gray-400",
    personality: "Musical",
    icon: Music,
    description: "Lives life to the rhythm",
  },
  {
    id: 7,
    character: "Cafe",
    emoji: "☕",
    color: "#030213",
    bgGradient: "from-gray-300 to-gray-400",
    personality: "Cozy",
    icon: Coffee,
    description: "Warm and welcoming",
  },
  {
    id: 8,
    character: "Stardust",
    emoji: "⭐",
    color: "#030213",
    bgGradient: "from-yellow-500 to-yellow-600",
    personality: "Magical",
    icon: Star,
    description: "Brings magic everywhere",
  },
  {
    id: 9,
    character: "Joy",
    emoji: "💖",
    color: "#030213",
    bgGradient: "from-red-300 to-red-400",
    personality: "Loving",
    icon: Heart,
    description: "Spreads love and kindness",
  },
  {
    id: 10,
    character: "Zen",
    emoji: "🧘",
    color: "#030213",
    bgGradient: "from-yellow-300 to-yellow-400",
    personality: "Peaceful",
    icon: Smile,
    description: "Calm and centered",
  },
  {
    id: 11,
    character: "Glitter",
    emoji: "✨",
    color: "#030213",
    bgGradient: "from-yellow-500 to-yellow-600",
    personality: "Sparkly",
    icon: Sparkles,
    description: "Shines bright like a diamond",
  },
];

export default cartoonAvatars;
